version: "3.8"

networks:
    scoring_system:
        driver: bridge

volumes:
    data:
        driver: local

services:
    php:
        build: ./docker/php/build
        networks: [scoring_system]
        volumes:
            - ./app/:/var/www/html/
            - /etc/timezone:/etc/timezone
        links: [database]
        env_file:
            - .env

    database:
        image: postgres:14.3-alpine
        networks: [scoring_system]
        ports: 
            - ${DATABASE_PORT}:5432
        volumes:
            - /etc/timezone:/etc/timezone
            - ./docker/database/data:/var/lib/postgresql/data
        env_file:
            - .env

    server:
        image: nginx:1.21-alpine
        ports:
            - ${HTTP_PORT}:80
            - ${HTTPS_PORT}:80
        networks: [scoring_system]
        links: [php]
        volumes:
            - ./app:/var/www/html
            - /etc/timezone:/etc/timezone
            - ./docker/server/log:/var/log/nginx
            - ./docker/server/config:/etc/nginx/conf.d
        restart: always

    adminer:
        image: adminer
        restart: always
        ports: 
          - ${ADMINER_PORT}:8080
        networks: [scoring_system]
