version: "3.8"

networks:
    scoring_system:
        driver: bridge

volumes:
    data:
        driver: local

services:
    php:
        build: ./docker/php/build
        networks: [scoring_system]
        volumes:
            - ./app/:/var/www/html/
            - /etc/timezone:/etc/timezone
        links: [database]
        env_file:
            - .env

    database:
        image: mysql:8.0.32-debian
        # restart: always
        networks: [scoring_system]
        ports: 
            - ${DATABASE_PORT}:3306
        volumes:
            - ./docker/database/data:/var/lib/mysql:delegated,rw
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "true"
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}

    server:
        image: nginx:1.21-alpine
        ports:
            - ${HTTP_PORT}:80
            - ${HTTPS_PORT}:80
        networks: [scoring_system]
        links: [php]
        volumes:
            - ./app:/var/www/html
            - /etc/timezone:/etc/timezone
            - ./docker/server/log:/var/log/nginx
            - ./docker/server/config:/etc/nginx/conf.d
        restart: always

    adminer:
        image: adminer
        restart: always
        ports: 
          - ${ADMINER_PORT}:8080
        networks: [scoring_system]
